language: java

jdk:
  - oraclejdk8
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  
notifications:
  email:
    recipients:
      - builds@starchartlabs.org
    on_success: never
    on_failure: always
